[run]
timeout = "1m"

[output]
format = "colored-line-number"

[linters]
disable-all = true
enable = ["gofumpt", "govet", "gci"]

[issues]
exclude-use-default = false

[linters-settings.gci]
sections = ["standard", "default", "prefix(github.com/gopherjs)"]
skip-generated = false
custom-order = true
